version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - LANG=C.UTF-8
    ports:
      - "${EXTERNAL_RAILS_PORT:-3000}:3000"
    tty: true
    volumes:
      - .:/myapp:cached
      - bundle:/usr/local/bundle
      - mysqld_sockets:/var/run/mysqld
    working_dir: /myapp

  db:
    image: mysql:5.7.24
    command: --character-set-server=utf8mb4
    environment:
      - LANG=C.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${EXTERNAL_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysqld_sockets:/var/run/mysqld

volumes:
  mysql_data:
  mysqld_sockets:
  bundle:
